### ISSUE TITLE
The module file format is too new to be used by this version of the debugger.

### ISSUE THREAD

**Issue by rahulbhalley** [tensorflow/swift-apis#1041] opened 2020-07-08 12:33 UTC
In my SPM's Package.swift, I add Files package:

```swift
.package(url: "https://github.com/JohnSundell/Files", from: "4.0.0"),
```

For the following code where the loop begins I get the error shown later.

```swift
do {
    let datasetName = "img_align_celeba"
    let datasetFolderPath = "Downloads/\(datasetName)/\(datasetName)/\(datasetName)"
    let datasetFolder = try Folder.home.subfolder(at: datasetFolderPath)
    print(datasetFolder)
    // var label = 0
    datasetFolder.subfolders.forEach { (folder: Folder) in
        folder.files.forEach { (file: File) in
            if file.name.hasSuffix(".jpg") {
                let imageURL = URL(fileURLWithPath: file.path)
                let image = Image(jpeg: imageURL)
                //        let resizedImage = image.resized(to: (imageHeight, imageWidth))
                let resizedImageTensor = Tensor(copying: image.tensor, to: device)
                images.append(resizedImageTensor)
            }
        }
    }
} catch {
    print(error)
}
```

Error:

```
/Users/rahulbhalley/Library/Developer/Xcode/DerivedData/MyLibrary2-bjaqnypxfdzmordbplehccxduzlz/Build/Products/Debug/MyLibrary2: Cannot load Swift type information; AST validation error in "MyLibrary2": The module file format is too new to be used by this version of the debugger.AST validation error in "Files": The module file format is too new to be used by this version of the debugger.AST validation error in "Files": The module file format is too new to be used by this version of the debugger.
Folder(name: img_align_celeba, path: /Users/rahulbhalley/Downloads/img_align_celeba/img_align_celeba/img_align_celeba/)
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.
Program ended with exit code: 9
```

What am I doing wrong? 🤔 It was working earlier (although I don't remember the version of `Files`). I created a new SPM too but in vain.

**Comment by dan-zheng** [comment] 2020-07-08 13:04
This seems like a potential duplicate of https://github.com/tensorflow/swift/issues/382. Though I'm not sure why your previously working workflow is now broken.

> This issue is tracked at [SR-12127](https://bugs.swift.org/browse/SR-12127). It's actually an issue in Xcode: Xcode uses system `lldb` instead of `lldb` from the active toolchain. The occurs even for [swift.org/download](https://swift.org/download) toolchains and isn't specific to Swift for TensorFlow.
> 
> Unfortunately, our team can't help fix this issue since Xcode is closed source.

You could try reporting the issue to Apple via Apple Bug Reporter. [This blog post](https://nshipster.com/bug-reporting) has more info on how to do that.

**Closed** 2020-07-08 17:06 UTC
