### ISSUE TITLE
Sequential causes Colab to crash

### ISSUE THREAD

**Issue by sjaz24** [tensorflow/swift-apis#542] opened 2019-11-04 19:57 UTC
I'm not totally sure if it's related to Sequential or something else but whenever I attempt to create a Sequential layer in Google Colab, the session crashes. Perhaps it's due to the usage of the function builder (LayerBuilder)???

<img width="970" alt="Screen Shot 2019-11-04 at 12 53 52 PM" src="https://user-images.githubusercontent.com/9062128/68153225-63269080-ff02-11e9-92b6-cf3684bd0b86.png">

**Comment by marcrasi** [comment] 2019-12-18 18:32
Do you know if this is reproducible on swift-jupyter running on a local machine? The crash in swift-jupyter might have slightly more informative error information.

Though if you don't have that set up, no worries, I'll try it myself eventually.

**Comment by BradLarson** [comment] 2020-12-28 22:20
I tried this with Colab kernels with and without various accelerators, and was unable to reproduce this with the current Swift Jupyter kernel and the 0.12 release toolchain. I'm guessing that whatever the cause was, it has been resolved by now.

Feel free to reopen this if I've missed something and / or if this recurs.

**Closed by BradLarson** 2020-12-28 22:20 UTC
