### ISSUE TITLE
Issue with applied(to:in:) differentiation

### ISSUE THREAD

**Issue by tanmayb123** [tensorflow/swift-apis#27] opened 2019-02-24 01:01 UTC
I've got this simple code:

```
import TensorFlow
enableGPU()

public struct test: Layer {

    @differentiable(wrt: (self, input))
    public func applied(to input: Tensor<Float>, in context: Context) -> Tensor<Float> {
        return input * 5
    }

}

public struct Generator: Layer {

    public typealias Input = Tensor<Float>
    public typealias Output = Tensor<Float>

    let tester = test()

    @differentiable(wrt: (self, input))
    public func applied(to input: Tensor<Float>, in context: Context) -> Tensor<Float> {
        let o1 = tester.applied(to: input, in: context)
        return o1
    }

}
```

However, I get the following error:

```
main.swift:20:27: error: can only differentiate with respect to parameters that conform to 'Differentiable', but 'Generator' does not conform to 'Differentiable'
    @differentiable(wrt: (self, input))
                          ^
main.swift:13:15: error: type 'Generator' does not conform to protocol 'Layer'
public struct Generator: Layer {
              ^
main.swift:21:17: note: candidate is missing attribute '@differentiable(wrt: (self, input))'
    public func applied(to input: Tensor<Float>, in context: Context) -> Tensor<Float> {
                ^
main.swift:13:15: error: type 'Generator' does not conform to protocol '__Differentiable'
public struct Generator: Layer {
              ^
Layer.swift:67:10: note: protocol requires function 'applied(to:in:)' with type '(Generator.Input, Context) -> Generator.Output' (aka '(Tensor<Float>, Context) -> Tensor<Float>'); do you want to add a stub?
    func applied(to input: Input, in context: Context) -> Output
         ^
Swift.__Differentiable:2:20: note: protocol requires nested type 'TangentVector'; do you want to add it?
    associatedtype TangentVector : AdditiveArithmetic
                   ^
Swift.__Differentiable:3:20: note: protocol requires nested type 'CotangentVector'; do you want to add it?
    associatedtype CotangentVector : AdditiveArithmetic
                   ^
Swift.__Differentiable:4:20: note: protocol requires nested type 'AllDifferentiableVariables'; do you want to add it?
    associatedtype AllDifferentiableVariables : Differentiable
                   ^
main.swift:13:15: error: type 'Generator' does not conform to protocol 'Differentiable'
public struct Generator: Layer {
              ^
main.swift:13:15: error: type 'Generator' does not conform to protocol '_Differentiable'
public struct Generator: Layer {
              ^
```

Did I do something wrong here?

**Comment by rxwei** [comment] 2019-02-24 01:24
This might be a bug in derived conformances. Can you try making ‘let tester’ be public?

**Comment by tanmayb123** [comment] 2019-02-24 02:15
Nope, same error.

**Comment by rxwei** [comment] 2019-02-24 03:09
That's a compiler bug. Would you mind filing a bug against the `AutoDiff` component at https://bugs.swift.org?

**Comment by tanmayb123** [comment] 2019-02-24 05:44
Sure thing @rxwei. I'll do that.

Another, really really simple reproducer:

```
import TensorFlow

public struct Test: Layer {

    public let abc = Dense<Float>(inputSize: 3, outputSize: 3, activation: { $0 })

    @differentiable(wrt: (self, input))
    public func applied(to input: Tensor<Float>, in context: Context) -> Tensor<Float> {
        return input * 3
    }

}
```

**Comment by rxwei** [comment] 2019-02-24 05:46
It actually looks like a regression -- it definitely worked in the past. We'll make sure to fix this ASAP.

**Comment by rxwei** [comment] 2019-02-24 05:47
cc @dan-zheng

**Comment by tanmayb123** [comment] 2019-02-24 05:47
When I download `Operators.swift` & `Layer.swift`, then I run `swiftc Operators.swift Layer.swift main.swift`, I get this:

```
main.swift:7:27: error: can only differentiate with respect to parameters that conform to 'Differentiable', but 'Test' does not conform to 'Differentiable'
    @differentiable(wrt: (self, input))
                          ^
main.swift:3:15: error: type 'Test' does not conform to protocol 'Layer'
public struct Test: Layer {
              ^
main.swift:3:15: error: type 'Test' does not conform to protocol '__Differentiable'
public struct Test: Layer {
              ^
Layer.swift:55:20: note: protocol requires nested type 'Input'; do you want to add it?
    associatedtype Input: Differentiable
                   ^
Layer.swift:57:20: note: protocol requires nested type 'Output'; do you want to add it?
    associatedtype Output: Differentiable
                   ^
Swift.__Differentiable:2:20: note: protocol requires nested type 'TangentVector'; do you want to add it?
    associatedtype TangentVector : AdditiveArithmetic
                   ^
Swift.__Differentiable:3:20: note: protocol requires nested type 'CotangentVector'; do you want to add it?
    associatedtype CotangentVector : AdditiveArithmetic
                   ^
Swift.__Differentiable:4:20: note: protocol requires nested type 'AllDifferentiableVariables'; do you want to add it?
    associatedtype AllDifferentiableVariables : Differentiable
                   ^
main.swift:3:15: error: type 'Test' does not conform to protocol 'Differentiable'
public struct Test: Layer {
              ^
main.swift:3:15: error: type 'Test' does not conform to protocol '_Differentiable'
public struct Test: Layer {
              ^
Stack dump:
0.	Program arguments: /root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift -frontend -c Operators.swift Layer.swift -primary-file main.swift -target x86_64-unknown-linux-gnu -disable-objc-interop -color-diagnostics -module-name main -o /tmp/main-a98d3a.o
1.	While type-checking protocol conformance to 'Differentiable' (in module 'Swift') for type 'Dense<Scalar>' (declared at [Layer.swift:193:8 - line:208:1] RangeText="struct Dense<Scalar: TensorFlowFloatingPoint>: Layer {
    public var weight: Tensor<Scalar>
    public var bias: Tensor<Scalar>
    public typealias Activation = @differentiable (Tensor<Scalar>) -> Tensor<Scalar>
    @noDerivative public let activation: Activation

    // FIXME(SR-9716): Remove this once the bug is fixed or worked around.
    public var allKeyPaths: [PartialKeyPath<Dense>] {
        return [\Dense.weight, \Dense.bias]
    }

    @differentiable(wrt: (self, input))
    public func applied(to input: Tensor<Scalar>, in _: Context) -> Tensor<Scalar> {
        return activation(matmul(input, weight) + bias)
    }
")
2.	While resolving requirement Swift.(file).__Differentiable.AllDifferentiableVariables in conformance <Scalar where Scalar : BinaryFloatingPoint, Scalar : Differentiable, Scalar : TensorFlowScalar> Dense<Scalar>: __Differentiable module main
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x433c0b4]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x4339e3e]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x433c272]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7f3b8b14e890]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x18f4950]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x167ad50]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x167684b]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x15addcd]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x15c1c11]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x15c1c9e]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x15c2c8e]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x15c3254]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x15c2a4c]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x15c60b5]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x15c668f]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x15c6986]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x15ada78]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x19a0e07]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x19a0a4e]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x19a1026]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x19a0ab2]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x19a03d8]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x19bdd30]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x19c4c74]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x19bfb15]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x19be081]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x19be9b7]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x158d2c0]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x158ca18]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x15a7c78]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x15c66d4]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x15a1e56]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x15a045e]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x159e0b3]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x15a96d9]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x15f0ecb]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x15f18cd]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0xd47040]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0xd45df0]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0xd45461]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x4c296e]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x4c1609]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x4721c0]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f3b76a0bb97]
/root/ss/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift[0x4705da]
<unknown>:0: error: unable to execute command: Segmentation fault
<unknown>:0: error: compile command failed due to signal 11 (use -v to see invocation)
```

**Comment by tanmayb123** [comment] 2019-02-24 10:13
Bug filed: https://bugs.swift.org/browse/TF-288

**Comment by tanmayb123** [comment] 2019-02-24 10:27
Found the problem: you can't have `abc` be a constant.

Replacing

`public let abc = Dense<Float>(inputSize: 3, outputSize: 3, activation: { $0 })`

with

`public var abc = Dense<Float>(inputSize: 3, outputSize: 3, activation: { $0 })`

makes the code compile.

**Comment by rxwei** [comment] 2019-02-24 10:28
Yes, that is known to be the cause. We have `var` tests everywhere so they shouldn't fail. Will debug this soon.

**Comment by rxwei** [comment] 2019-02-27 19:59
This has been fixed in https://github.com/apple/swift/pull/22905.

**Closed by rxwei** 2019-02-27 19:59 UTC
